---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: add users
      user:
        name: "{{ item }}"
        state: present
        generate_ssh_key: yes
      with_items:
        - kuku
        - lola
        - nena
