---
- name: create files larger than 2G
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: create a file that is larger than 2GB
      shell: dd if=/dev/urandom of=/tmp/file.txt bs=2200000 count=1000
