---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name:
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - telnet
        - httpd
        - tree
