---
- name: patching kernel
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: get the hostname
      hostname:
        name: "{{hostname}}"

    - name: confirm kernel version
      # vars:
      #   kernel_version: "{{kernel}}"
      #   register: current_kernel
      # - debug: msg="{{ current_kernel.kernel }}"
      shell: uname -a
      register: kernel_version
    - debug: var=kernel_version.stdout

    - name: update system
      yum:
        name: "*"
        state: latest
