---
- name: patching kernel
  hosts: "{{hostname}}"
  become: yes
  become_method: sudo
  tasks:

    - name: confirm kernel version
      # vars:
      #   kernel_version: "{{kernel}}"
      #   register: current_kernel
      # - debug: msg="{{ current_kernel.kernel }}"
      shell: uname -a
      register: kernel_version
    - debug: var=kernel_version.stdout

    - name: update system
      yum:
        name: "*"
        state: latest
    - name: download kernel
      get_url:
        url: https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.4.23.tar.xz
        dest: /tmp/linux-{{ kernel_ver }}.tar.xz

    - name: untar kernel
      shell: tar -Jxvf linux-{{ kernel_ver }}.tar.xz
      args:
        chdir: /tmp/


    - name: install kernel
      shell: "{{ item }}"
      with_items:
      - make silentoldconfig .config
      - make
      - make modules
      - make modules_install
      - make install
      args:
        chdir: /tmp/linux-{{ kernel_ver }}/


    - name: restart machine
      shell: sleep 2 && shutdown -r +1 "Ansible updates triggered"
      async: 1
      poll: 0
      sudo: true
      ignore_errors: true

    - name: waiting for server to come back
      local_action: wait_for host={{hostname}} state=started delay=30 timeout=300
      sudo: false

    - name: confirm kernel version
      shell: uname -a
      register: kernel_version

    - debug: var=kernel_version.stdout
