---
- name: patching kernel
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: get the hostname
      hostname:
        name: "{{hostname}}"

    - name: confirm kernel version
      shell: uname -a
      register: kernel_version

    - name: update system
      yum:
        name: "*"
        state: latest
