---
- name: patching kernel
  hosts: "{{hostname}}"
  become: yes
  become_method: sudo
  tasks:

    - name: confirm kernel version
      # vars:
      #   kernel_version: "{{kernel}}"
      #   register: current_kernel
      # - debug: msg="{{ current_kernel.kernel }}"
      shell: uname -a
      register: kernel_version
    - debug: var=kernel_version.stdout


    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: http://mirror.centos.org/centos/7/os/x86_64/Packages/abrt-addon-kerneloops-2.1.11-52.el7.centos.x86_64.rpm

    - name: update system
      yum:
        name: "*"
        state: latest



    - name: restart machine
      shell: sleep 2 && shutdown -r +1 "Ansible updates triggered"
      async: 1
      poll: 0
      sudo: true
      ignore_errors: true

    - name: waiting for server to come back
      local_action: wait_for host={{hostname}} state=started delay=30 timeout=300
      sudo: false

    - name: confirm kernel version
      shell: uname -a
      register: kernel_version

    - debug: var=kernel_version.stdout
