---
- name: find /tmp files older than 90 days
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: finding files that are 90 days old
      find:
        paths: /tmp
        age: 90d
        recurse: yes
      register: found
    - name: Compress files
      archive:
        path: "{{found.files|map(attribute='path')|list}}"
        format: gz
        dest: "/tmp/file{{ansible_date_time.date}}.90daysold.tgz"
